#!/usr/bin/env python3
"""
Daily Market Report Generator
Claude API + Web Search で市況データを取得し、HTMLレポートを生成する。
"""

import anthropic
import datetime
import re

def get_japan_date():
    """日本時間の日付を取得"""
    utc_now = datetime.datetime.now(datetime.timezone.utc)
    jst = datetime.timezone(datetime.timedelta(hours=9))
    jst_now = utc_now.astimezone(jst)
    weekdays = ["月", "火", "水", "木", "金", "土", "日"]
    wd = weekdays[jst_now.weekday()]
    return jst_now.strftime(f"%-m/%-d（{wd}）朝")

def generate_report():
    client = anthropic.Anthropic()
    
    japan_date = get_japan_date()
    
    prompt = f"""あなたは金融市場のアナリストです。今日の日付は{japan_date}（日本時間）です。

以下の手順でマーケットレポートHTMLを生成してください。

## Step 1: Web検索で最新の市況データを取得
以下の6項目の最新値と前日比（%）を検索してください:
1. S&P 500
2. 日経平均
3. NY原油 WTI
4. 天然ガス（TTF or Henry Hub）
5. NY金先物
6. ドル円 為替レート

## Step 2: Web検索でマーケットニュースを3〜5本取得
株式・商品・為替に関連する今日の主要ニュースを検索してまとめてください。

## Step 3: 以下の仕様に従ってHTMLを生成
- 完全な単一HTMLファイル（CSS・JSすべてインライン）
- <!DOCTYPE html>から</html>まで完全に出力すること
- 余計な説明文は不要、HTMLコードのみ出力

### デザイン仕様:
- ヘッダー: 濃紺(#1a2744)背景、白文字、「🇺🇸 NY市況 & マーケットサマリー」、右側に日付「{japan_date}」
- 市況カード: 2列グリッド、6カード（S&P500, 日経平均, NY原油, 天然ガス, NY金, ドル円）
  - 各カードにラベル（淡色背景#f0ede8）、数値（28px bold）、変動率バッジ
  - プラスは緑(#16a34a)、マイナスは赤(#dc2626)のバッジ
- ニュースセクション: 「ニュースひとめで」見出し、3〜5トピック
  - 各トピック: 青(#2c4a7c)背景のヘッダー、▸付きポイント、重要語は赤太字
- フッター: 「Generated by Claude · データはWeb検索に基づく速報値」
- フォント: "Noto Sans JP", "Hiragino Sans", sans-serif
- max-width: 700px, 中央寄せ
- レスポンシブ対応（700px以下で1列）
- body背景: #e8e4df

HTMLコードのみを出力してください。```html等のマークダウン記法は使わないでください。
"""

    response = client.messages.create(
        model="claude-sonnet-4-20250514",
        max_tokens=8000,
        tools=[{
            "type": "web_search_20250305",
            "name": "web_search",
        }],
        messages=[{"role": "user", "content": prompt}]
    )

    # レスポンスからHTMLを抽出
    html_content = ""
    for block in response.content:
        if block.type == "text":
            html_content += block.text

    # マークダウンのコードブロックが含まれている場合は除去
    html_content = html_content.strip()
    if html_content.startswith("```html"):
        html_content = html_content[7:]
    if html_content.startswith("```"):
        html_content = html_content[3:]
    if html_content.endswith("```"):
        html_content = html_content[:-3]
    html_content = html_content.strip()

    # <!DOCTYPE から始まるように調整
    doctype_idx = html_content.lower().find("<!doctype")
    if doctype_idx > 0:
        html_content = html_content[doctype_idx:]

    # 結果を保存
    with open("index.html", "w", encoding="utf-8") as f:
        f.write(html_content)

    print(f"Report generated successfully for {japan_date}")
    print(f"HTML size: {len(html_content)} bytes")

if __name__ == "__main__":
    generate_report()
